# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1632, 1017)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/hotel design 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("style sheet\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTreeView, QListView\n"
"{\n"
"    background-color: silver;\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 1px solid darkgray;*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 17px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/dark_orange/img/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 1px solid darkgray;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/dark_orange/img/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 8px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #3A3939;\n"
"    width: 8px;\n"
"    background: #201F1F;\n"
"    margin: 0 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
"      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: 0 -4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid darkgray;\n"
"\n"
"    border-radius: 2px;\n"
"    min-width: 50px;\n"
"}\n"
"QToolBox  {\n"
"    padding: 5px;\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    color: #eff0f1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent #323232;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    font: italic;\n"
"    background-color: #323232;\n"
"    border-color: #D1DBCB;\n"
" }\n"
"QComboBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1610, 944))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setLineWidth(4)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_3.addWidget(self.textEdit_2, 4, 4, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_16.addWidget(self.checkBox_3, 9, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_16.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_23.setLineWidth(5)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/LKIHNL.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_16.addWidget(self.label_23, 5, 0, 3, 2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_16.addWidget(self.checkBox, 10, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_16.addWidget(self.checkBox_2, 11, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_16.addWidget(self.pushButton_5, 11, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_4, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 5, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_3, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_20.setLineWidth(5)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/caar.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 4, 2, 5, 1)
        self.listView_2 = QtWidgets.QListView(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_2.sizePolicy().hasHeightForWidth())
        self.listView_2.setSizePolicy(sizePolicy)
        self.listView_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_15.addWidget(self.listView_2, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 4, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_15.addWidget(self.pushButton_6, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 6, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_5, 6, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_15.addWidget(self.label_39, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 3, 1, 2)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(3)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_29.setLineWidth(5)
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/gym2.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 1, 0, 3, 3)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_17.addWidget(self.timeEdit_2, 4, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_17.addWidget(self.label_40, 0, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 4, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_17.addWidget(self.pushButton_4, 4, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_8, 3, 0, 3, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(3)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_49 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_10.addWidget(self.label_49, 2, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_10.addWidget(self.label_44, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_27.setLineWidth(5)
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/SERV.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 4)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timeEdit_4.setFont(font)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout_10.addWidget(self.timeEdit_4, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 5, 4, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(3)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_47 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 3, 0, 1, 1)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timeEdit_3.setFont(font)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout_11.addWidget(self.timeEdit_3, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_11.addWidget(self.pushButton_8, 3, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_7)
        self.label_30.setFrameShape(QtWidgets.QFrame.Box)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_30.setLineWidth(5)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/party.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 2, 0, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 3, 3, 3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(464, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setMouseTracking(False)
        self.groupBox_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 127);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_14.setText("")
        self.radioButton_14.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_12.addWidget(self.radioButton_14)
        self.label_114 = QtWidgets.QLabel(self.groupBox_2)
        self.label_114.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_114.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_114.setLineWidth(5)
        self.label_114.setText("")
        self.label_114.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_114.setScaledContents(True)
        self.label_114.setObjectName("label_114")
        self.horizontalLayout_12.addWidget(self.label_114)
        self.label_115 = QtWidgets.QLabel(self.groupBox_2)
        self.label_115.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_115.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_115.setLineWidth(5)
        self.label_115.setText("")
        self.label_115.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_115.setScaledContents(True)
        self.label_115.setObjectName("label_115")
        self.horizontalLayout_12.addWidget(self.label_115)
        self.label_116 = QtWidgets.QLabel(self.groupBox_2)
        self.label_116.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_116.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_116.setLineWidth(5)
        self.label_116.setText("")
        self.label_116.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_116.setScaledContents(True)
        self.label_116.setObjectName("label_116")
        self.horizontalLayout_12.addWidget(self.label_116)
        self.label_117 = QtWidgets.QLabel(self.groupBox_2)
        self.label_117.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_117.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_117.setLineWidth(5)
        self.label_117.setText("")
        self.label_117.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_117.setScaledContents(True)
        self.label_117.setObjectName("label_117")
        self.horizontalLayout_12.addWidget(self.label_117)
        self.label_118 = QtWidgets.QLabel(self.groupBox_2)
        self.label_118.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_118.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_118.setLineWidth(5)
        self.label_118.setText("")
        self.label_118.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_118.setScaledContents(True)
        self.label_118.setObjectName("label_118")
        self.horizontalLayout_12.addWidget(self.label_118)
        self.label_136 = QtWidgets.QLabel(self.groupBox_2)
        self.label_136.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_136.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_136.setLineWidth(5)
        self.label_136.setText("")
        self.label_136.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_136.setScaledContents(True)
        self.label_136.setObjectName("label_136")
        self.horizontalLayout_12.addWidget(self.label_136)
        self.label_130 = QtWidgets.QLabel(self.groupBox_2)
        self.label_130.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_130.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_130.setLineWidth(5)
        self.label_130.setText("")
        self.label_130.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_130.setScaledContents(True)
        self.label_130.setObjectName("label_130")
        self.horizontalLayout_12.addWidget(self.label_130)
        self.label_129 = QtWidgets.QLabel(self.groupBox_2)
        self.label_129.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_129.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_129.setLineWidth(5)
        self.label_129.setText("")
        self.label_129.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_129.setScaledContents(True)
        self.label_129.setObjectName("label_129")
        self.horizontalLayout_12.addWidget(self.label_129)
        self.label_119 = QtWidgets.QLabel(self.groupBox_2)
        self.label_119.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_119.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_119.setLineWidth(5)
        self.label_119.setText("")
        self.label_119.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_119.setScaledContents(True)
        self.label_119.setObjectName("label_119")
        self.horizontalLayout_12.addWidget(self.label_119)
        self.label_120 = QtWidgets.QLabel(self.groupBox_2)
        self.label_120.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_120.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_120.setLineWidth(5)
        self.label_120.setText("")
        self.label_120.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_120.setScaledContents(True)
        self.label_120.setObjectName("label_120")
        self.horizontalLayout_12.addWidget(self.label_120)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_12.setText("")
        self.radioButton_12.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_10.addWidget(self.radioButton_12)
        self.label_100 = QtWidgets.QLabel(self.groupBox_2)
        self.label_100.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_100.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_100.setLineWidth(5)
        self.label_100.setText("")
        self.label_100.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_100.setScaledContents(True)
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_10.addWidget(self.label_100)
        self.label_101 = QtWidgets.QLabel(self.groupBox_2)
        self.label_101.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_101.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_101.setLineWidth(5)
        self.label_101.setText("")
        self.label_101.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_101.setScaledContents(True)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_10.addWidget(self.label_101)
        self.label_102 = QtWidgets.QLabel(self.groupBox_2)
        self.label_102.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_102.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_102.setLineWidth(5)
        self.label_102.setText("")
        self.label_102.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_102.setScaledContents(True)
        self.label_102.setObjectName("label_102")
        self.horizontalLayout_10.addWidget(self.label_102)
        self.label_103 = QtWidgets.QLabel(self.groupBox_2)
        self.label_103.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_103.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_103.setLineWidth(5)
        self.label_103.setText("")
        self.label_103.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_103.setScaledContents(True)
        self.label_103.setObjectName("label_103")
        self.horizontalLayout_10.addWidget(self.label_103)
        self.label_104 = QtWidgets.QLabel(self.groupBox_2)
        self.label_104.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_104.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_104.setLineWidth(5)
        self.label_104.setText("")
        self.label_104.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_104.setScaledContents(True)
        self.label_104.setObjectName("label_104")
        self.horizontalLayout_10.addWidget(self.label_104)
        self.label_132 = QtWidgets.QLabel(self.groupBox_2)
        self.label_132.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_132.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_132.setLineWidth(5)
        self.label_132.setText("")
        self.label_132.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_132.setScaledContents(True)
        self.label_132.setObjectName("label_132")
        self.horizontalLayout_10.addWidget(self.label_132)
        self.label_105 = QtWidgets.QLabel(self.groupBox_2)
        self.label_105.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_105.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_105.setLineWidth(5)
        self.label_105.setText("")
        self.label_105.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_105.setScaledContents(True)
        self.label_105.setObjectName("label_105")
        self.horizontalLayout_10.addWidget(self.label_105)
        self.label_106 = QtWidgets.QLabel(self.groupBox_2)
        self.label_106.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_106.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_106.setLineWidth(5)
        self.label_106.setText("")
        self.label_106.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_106.setScaledContents(True)
        self.label_106.setObjectName("label_106")
        self.horizontalLayout_10.addWidget(self.label_106)
        self.label_126 = QtWidgets.QLabel(self.groupBox_2)
        self.label_126.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_126.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_126.setLineWidth(5)
        self.label_126.setText("")
        self.label_126.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_126.setScaledContents(True)
        self.label_126.setObjectName("label_126")
        self.horizontalLayout_10.addWidget(self.label_126)
        self.label_125 = QtWidgets.QLabel(self.groupBox_2)
        self.label_125.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_125.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_125.setLineWidth(5)
        self.label_125.setText("")
        self.label_125.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_125.setScaledContents(True)
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_10.addWidget(self.label_125)
        self.gridLayout_12.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_11.setText("")
        self.radioButton_11.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_9.addWidget(self.radioButton_11)
        self.label_93 = QtWidgets.QLabel(self.groupBox_2)
        self.label_93.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_93.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_93.setLineWidth(5)
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_93.setScaledContents(True)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_9.addWidget(self.label_93)
        self.label_94 = QtWidgets.QLabel(self.groupBox_2)
        self.label_94.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_94.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_94.setLineWidth(5)
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_9.addWidget(self.label_94)
        self.label_95 = QtWidgets.QLabel(self.groupBox_2)
        self.label_95.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_95.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_95.setLineWidth(5)
        self.label_95.setText("")
        self.label_95.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_95.setScaledContents(True)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_9.addWidget(self.label_95)
        self.label_96 = QtWidgets.QLabel(self.groupBox_2)
        self.label_96.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_96.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_96.setLineWidth(5)
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_9.addWidget(self.label_96)
        self.label_97 = QtWidgets.QLabel(self.groupBox_2)
        self.label_97.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_97.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_97.setLineWidth(5)
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_97.setScaledContents(True)
        self.label_97.setObjectName("label_97")
        self.horizontalLayout_9.addWidget(self.label_97)
        self.label_133 = QtWidgets.QLabel(self.groupBox_2)
        self.label_133.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_133.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_133.setLineWidth(5)
        self.label_133.setText("")
        self.label_133.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_133.setScaledContents(True)
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_9.addWidget(self.label_133)
        self.label_98 = QtWidgets.QLabel(self.groupBox_2)
        self.label_98.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_98.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_98.setLineWidth(5)
        self.label_98.setText("")
        self.label_98.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_98.setScaledContents(True)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_9.addWidget(self.label_98)
        self.label_124 = QtWidgets.QLabel(self.groupBox_2)
        self.label_124.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_124.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_124.setLineWidth(5)
        self.label_124.setText("")
        self.label_124.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_124.setScaledContents(True)
        self.label_124.setObjectName("label_124")
        self.horizontalLayout_9.addWidget(self.label_124)
        self.label_123 = QtWidgets.QLabel(self.groupBox_2)
        self.label_123.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_123.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_123.setLineWidth(5)
        self.label_123.setText("")
        self.label_123.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_123.setScaledContents(True)
        self.label_123.setObjectName("label_123")
        self.horizontalLayout_9.addWidget(self.label_123)
        self.label_99 = QtWidgets.QLabel(self.groupBox_2)
        self.label_99.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_99.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_99.setLineWidth(5)
        self.label_99.setText("")
        self.label_99.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_99.setScaledContents(True)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_9.addWidget(self.label_99)
        self.gridLayout_12.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_13.setText("")
        self.radioButton_13.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_11.addWidget(self.radioButton_13)
        self.label_107 = QtWidgets.QLabel(self.groupBox_2)
        self.label_107.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_107.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_107.setLineWidth(5)
        self.label_107.setText("")
        self.label_107.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_107.setScaledContents(True)
        self.label_107.setObjectName("label_107")
        self.horizontalLayout_11.addWidget(self.label_107)
        self.label_108 = QtWidgets.QLabel(self.groupBox_2)
        self.label_108.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_108.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_108.setLineWidth(5)
        self.label_108.setText("")
        self.label_108.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_108.setScaledContents(True)
        self.label_108.setObjectName("label_108")
        self.horizontalLayout_11.addWidget(self.label_108)
        self.label_109 = QtWidgets.QLabel(self.groupBox_2)
        self.label_109.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_109.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_109.setLineWidth(5)
        self.label_109.setText("")
        self.label_109.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_109.setScaledContents(True)
        self.label_109.setObjectName("label_109")
        self.horizontalLayout_11.addWidget(self.label_109)
        self.label_131 = QtWidgets.QLabel(self.groupBox_2)
        self.label_131.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_131.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_131.setLineWidth(5)
        self.label_131.setText("")
        self.label_131.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_131.setScaledContents(True)
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_11.addWidget(self.label_131)
        self.label_135 = QtWidgets.QLabel(self.groupBox_2)
        self.label_135.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_135.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_135.setLineWidth(5)
        self.label_135.setText("")
        self.label_135.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_135.setScaledContents(True)
        self.label_135.setObjectName("label_135")
        self.horizontalLayout_11.addWidget(self.label_135)
        self.label_111 = QtWidgets.QLabel(self.groupBox_2)
        self.label_111.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_111.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_111.setLineWidth(5)
        self.label_111.setText("")
        self.label_111.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_111.setScaledContents(True)
        self.label_111.setObjectName("label_111")
        self.horizontalLayout_11.addWidget(self.label_111)
        self.label_128 = QtWidgets.QLabel(self.groupBox_2)
        self.label_128.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_128.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_128.setLineWidth(5)
        self.label_128.setText("")
        self.label_128.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_128.setScaledContents(True)
        self.label_128.setObjectName("label_128")
        self.horizontalLayout_11.addWidget(self.label_128)
        self.label_127 = QtWidgets.QLabel(self.groupBox_2)
        self.label_127.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_127.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_127.setLineWidth(5)
        self.label_127.setText("")
        self.label_127.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_127.setScaledContents(True)
        self.label_127.setObjectName("label_127")
        self.horizontalLayout_11.addWidget(self.label_127)
        self.label_112 = QtWidgets.QLabel(self.groupBox_2)
        self.label_112.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_112.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_112.setLineWidth(5)
        self.label_112.setText("")
        self.label_112.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_112.setScaledContents(True)
        self.label_112.setObjectName("label_112")
        self.horizontalLayout_11.addWidget(self.label_112)
        self.label_113 = QtWidgets.QLabel(self.groupBox_2)
        self.label_113.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_113.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_113.setLineWidth(5)
        self.label_113.setText("")
        self.label_113.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_113.setScaledContents(True)
        self.label_113.setObjectName("label_113")
        self.horizontalLayout_11.addWidget(self.label_113)
        self.gridLayout_12.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_89 = QtWidgets.QLabel(self.groupBox_2)
        self.label_89.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_89.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_89.setLineWidth(5)
        self.label_89.setText("")
        self.label_89.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_89.setScaledContents(True)
        self.label_89.setObjectName("label_89")
        self.gridLayout_13.addWidget(self.label_89, 0, 4, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.groupBox_2)
        self.label_90.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_90.setLineWidth(5)
        self.label_90.setText("")
        self.label_90.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName("label_90")
        self.gridLayout_13.addWidget(self.label_90, 0, 5, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.groupBox_2)
        self.label_88.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_88.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_88.setLineWidth(5)
        self.label_88.setText("")
        self.label_88.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName("label_88")
        self.gridLayout_13.addWidget(self.label_88, 0, 3, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_2)
        self.label_92.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_92.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_92.setLineWidth(5)
        self.label_92.setText("")
        self.label_92.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName("label_92")
        self.gridLayout_13.addWidget(self.label_92, 0, 10, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.groupBox_2)
        self.label_87.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_87.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_87.setLineWidth(5)
        self.label_87.setText("")
        self.label_87.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName("label_87")
        self.gridLayout_13.addWidget(self.label_87, 0, 2, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.groupBox_2)
        self.label_122.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_122.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_122.setLineWidth(5)
        self.label_122.setText("")
        self.label_122.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_122.setScaledContents(True)
        self.label_122.setObjectName("label_122")
        self.gridLayout_13.addWidget(self.label_122, 0, 8, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_10.setText("")
        self.radioButton_10.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_13.addWidget(self.radioButton_10, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_76.setLineWidth(5)
        self.label_76.setText("")
        self.label_76.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/star.png"))
        self.label_76.setScaledContents(True)
        self.label_76.setObjectName("label_76")
        self.gridLayout_13.addWidget(self.label_76, 0, 1, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.groupBox_2)
        self.label_121.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_121.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_121.setLineWidth(5)
        self.label_121.setText("")
        self.label_121.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_121.setScaledContents(True)
        self.label_121.setObjectName("label_121")
        self.gridLayout_13.addWidget(self.label_121, 0, 9, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.groupBox_2)
        self.label_91.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_91.setLineWidth(5)
        self.label_91.setText("")
        self.label_91.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_91.setScaledContents(True)
        self.label_91.setObjectName("label_91")
        self.gridLayout_13.addWidget(self.label_91, 0, 6, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.groupBox_2)
        self.label_134.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_134.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_134.setLineWidth(5)
        self.label_134.setText("")
        self.label_134.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/anti star.png"))
        self.label_134.setScaledContents(True)
        self.label_134.setObjectName("label_134")
        self.gridLayout_13.addWidget(self.label_134, 0, 7, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 4, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(3)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timeEdit_5.setFont(font)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.gridLayout_9.addWidget(self.timeEdit_5, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_9.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_5)
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_28.setLineWidth(5)
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/SPA2.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 0, 1, 3)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(52, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_9.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 3, 2, 3, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(220)
        sizePolicy.setVerticalStretch(180)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(220, 180))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_16.setLineWidth(7)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/logo 2.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 4, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_50.setFrameShape(QtWidgets.QFrame.Box)
        self.label_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_50.setLineWidth(7)
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap(":/newPrefix/check in_qrc/SEEE.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 0, 2, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1632, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "we will be blessed if you\'d like to write your review and recommendations . "))
        self.checkBox_3.setText(_translate("MainWindow", "Breakfast"))
        self.label_41.setText(_translate("MainWindow", "Meals in room"))
        self.checkBox.setText(_translate("MainWindow", "Lunch"))
        self.checkBox_2.setText(_translate("MainWindow", "Dinner"))
        self.pushButton_5.setText(_translate("MainWindow", "Ask Now"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "White"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "White"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Grey"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Dark Blue"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Black"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Red"))
        self.label_18.setText(_translate("MainWindow", "color"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "BMW i8 Roadster"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "BMW i8 Roadster"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Peugeot 508 "))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Tesla Model S "))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Toyota RAV4 "))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Nissan GT-R "))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Ford Mustang GT "))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Toyota Hilux"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Audi e-tron"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Jaguar F-Pace "))
        self.label_17.setText(_translate("MainWindow", "Car Type"))
        self.pushButton_6.setText(_translate("MainWindow", "Ask Now"))
        self.label_21.setText(_translate("MainWindow", "model"))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "2020"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "2020"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2019"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "2018"))
        self.label_22.setText(_translate("MainWindow", "Total cost"))
        self.label_39.setText(_translate("MainWindow", "Car Rental"))
        self.label_40.setText(_translate("MainWindow", "GYM"))
        self.label_19.setText(_translate("MainWindow", "Time Required"))
        self.pushButton_4.setText(_translate("MainWindow", "Ask Now"))
        self.label_49.setText(_translate("MainWindow", "Time Required"))
        self.label_44.setText(_translate("MainWindow", "Room Services"))
        self.pushButton_3.setText(_translate("MainWindow", "Ask Now"))
        self.pushButton_2.setText(_translate("MainWindow", "Rate"))
        self.label_47.setText(_translate("MainWindow", "Time Required"))
        self.pushButton_8.setText(_translate("MainWindow", "Ask Now"))
        self.label_42.setText(_translate("MainWindow", "Special parties"))
        self.label.setText(_translate("MainWindow", "    Rate Us:"))
        self.label_43.setText(_translate("MainWindow", "spa                      "))
        self.label_48.setText(_translate("MainWindow", "Time Required"))
        self.pushButton_7.setText(_translate("MainWindow", "Ask Now"))
import check_in_rc
